In [58]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor

In [59]:
data= pd.read_csv("household_power_consumption.txt",sep = ";", low_memory=False)

In [60]:
data.head()

Date      Time Global_active_power Global_reactive_power  Voltage  \
0  16/12/2006  17:24:00               4.216                 0.418  234.840   
1  16/12/2006  17:25:00               5.360                 0.436  233.630   
2  16/12/2006  17:26:00               5.374                 0.498  233.290   
3  16/12/2006  17:27:00               5.388                 0.502  233.740   
4  16/12/2006  17:28:00               3.666                 0.528  235.680   

  Global_intensity Sub_metering_1 Sub_metering_2  Sub_metering_3  
0           18.400          0.000          1.000            17.0  
1           23.000          0.000          1.000            16.0  
2           23.000          0.000          2.000            17.0  
3           23.000          0.000          1.000            17.0  
4           15.800          0.000          1.000            17.0

In [61]:
data.isnull().sum()

Date                         0
Time                         0
Global_active_power          0
Global_reactive_power        0
Voltage                      0
Global_intensity             0
Sub_metering_1               0
Sub_metering_2               0
Sub_metering_3           25979
dtype: int64

In [62]:
data=data.replace("?","nan")
data.dropna(inplace= True)

In [63]:
data.isnull().sum()

Date                     0
Time                     0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64

In [64]:
data_new=data.iloc[0:30000,]

In [65]:
# dataset1["Global_active_power"]= dataset1["Global_active_power"].astype("float")
# dataset["Voltage"]= dataset["Voltage"].astype("float")
# dataset["Global_intensity"]= dataset["Global_intensity"].astype("float")
data_new=data_new.iloc[:,2:].astype("float")
data_new

Global_active_power  Global_reactive_power  Voltage  Global_intensity  \
0                    4.216                  0.418   234.84              18.4   
1                    5.360                  0.436   233.63              23.0   
2                    5.374                  0.498   233.29              23.0   
3                    5.388                  0.502   233.74              23.0   
4                    3.666                  0.528   235.68              15.8   
...                    ...                    ...      ...               ...   
29999                1.562                  0.000   237.18               6.8   
30000                1.574                  0.000   238.17               6.8   
30001                1.580                  0.000   239.05               6.8   
30002                1.580                  0.000   238.87               6.8   
30003                1.586                  0.000   239.29               6.8   

       Sub_metering_1  Sub_metering_2  Sub_metering_3  
0                 0.0             1.0            17.0  
1                 0.0             1.0            16.0  
2                 0.0             2.0            17.0  
3                 0.0             1.0            17.0  
4                 0.0             1.0            17.0  
...               ...             ...             ...  
29999             0.0             0.0            17.0  
30000             0.0             0.0            17.0  
30001             0.0             0.0            18.0  
30002             0.0             0.0            17.0  
30003             0.0             0.0            18.0  

[30000 rows x 7 columns]

In [66]:
X= data_new.iloc[:,2:4].values

y=data_new.iloc[:,0].values



In [67]:
X

array([[234.84,  18.4 ],
       [233.63,  23.  ],
       [233.29,  23.  ],
       ...,
       [239.05,   6.8 ],
       [238.87,   6.8 ],
       [239.29,   6.8 ]])

In [69]:
y = y.reshape(len(y),1)
y

array([[4.216],
       [5.36 ],
       [5.374],
       ...,
       [1.58 ],
       [1.58 ],
       [1.586]])

In [74]:
#Scaling of Data
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train).round(1)
# X_test = sc.transform(X_test).round(1)
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [75]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 36)


In [76]:
X_train

array([[ 0.00408625, -1.044817  ],
       [ 0.12265853,  0.50217455],
       [-0.04442059, -1.044817  ],
       ...,
       [-0.01477752, -0.65806911],
       [ 0.89068353,  0.15058556],
       [ 0.61042177, -1.0799759 ]])

In [77]:
models=[
    {
        "label": "Linear Regg",
        "model": LinearRegression(),
    },
    # {
    #     "label": "Polynomial Regg",
    #     "model": PolynomialFeatures(degree = 4),
    # },
    {
        "label": "SVR RBF",
        "model": SVR(kernel = 'rbf'),
    },
    {
        "label": "SVR Poly",
        "model": SVR(kernel = 'poly'),
    },
    {
        "label": "Decision Tree",
        "model": DecisionTreeRegressor(random_state = 0)      
    },
    {
        "label": "Random Forest",
        "model": RandomForestRegressor(n_estimators = 10, random_state = 0)
    },
    
    ]

for m in models:
    model= m["model"]
    model.fit(X_train, y_train.ravel())
    y_pred= model.predict(X_test)
    print(r2_score(y_test, y_pred))
    print()  
      

0.9972962332503494

0.9952803768071291

0.43347707471518604

0.9967056615765626

0.9974348252382779

