<a href="https://colab.research.google.com/github/nitver90/Machine-Learning-Repo/blob/main/Hydraulic%20Dataset/Hydraulic_Data_Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
data= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Hydraulic Dataset/Hydraulic Data.csv")

X=data.iloc[:,:-5].values
y=data.iloc[:,-5].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
#Training Data
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [7]:
y_pred= classifier.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy Score:", accuracy_score(y_test,y_pred))
print("Precision Score:", precision_score(y_test,y_pred, average="weighted"))
print("Recall Score:", recall_score(y_test,y_pred, average="weighted"))

[[199   0   0]
 [  0 181   0]
 [  0   1 171]]
Accuracy Score: 0.9981884057971014
Precision Score: 0.9981983596114031
Recall Score: 0.9981884057971014
