<a href="https://colab.research.google.com/github/nitver90/Machine-Learning-Repo/blob/main/Hydraulic%20Dataset/Hydraulic_Data_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


In [3]:
data= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Hydraulic Dataset/Hydraulic Data.csv")

X=data.iloc[:,:-5].values
y=data.iloc[:,-5].values


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
from sklearn.ensemble import RandomForestClassifier
classifier_RF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_RF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [7]:
y_pred = classifier_RF.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy Score:", accuracy_score(y_test,y_pred))
print("Precision Score:", precision_score(y_test,y_pred, average="weighted"))
print("Recall Score:", recall_score(y_test,y_pred, average="weighted"))

[[199   0   0]
 [  0 181   0]
 [  0   1 171]]
Accuracy Score: 0.9981884057971014
Precision Score: 0.9981983596114031
Recall Score: 0.9981884057971014
