<a href="https://colab.research.google.com/github/nitver90/Machine-Learning-Repo/blob/main/Hydraulic%20Dataset/Hydraulic_Data_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Hydraulic Dataset/Hydraulic Data.csv")

X=data.iloc[:,:-5].values
y=data.iloc[:,-5].values


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
#Training Data
from sklearn.naive_bayes import GaussianNB
classifier_NB= GaussianNB()
classifier_NB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
y_pred= classifier_NB.predict(X_test)

In [10]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Precision Score:", precision_score(y_test, y_pred, average="weighted"))
print("Recall Score:", recall_score(y_test, y_pred, average="weighted"))

[[199   0   0]
 [  2 179   0]
 [  0   1 171]]
Accuracy Score:  0.9945652173913043
Precision Score: 0.9945912046049944
Recall Score: 0.9945652173913043
