<a href="https://colab.research.google.com/github/nitver90/Machine-Learning-Repo/blob/main/Hydraulic%20Dataset/Hydraulic_Data_Making_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data= pd.read_csv ("D:\ML\Hydrolic Data\CE.txt",sep="\t", header=None)              ##Given Local Address in terminal. 

In [ ]:
data.head()

0       1       2       3       4       5       6       7       8   \
0  47.202  47.273  47.250  47.332  47.213  47.372  47.273  47.438  46.691   
1  29.208  28.822  28.805  28.922  28.591  28.643  28.216  27.812  27.514   
2  23.554  23.521  23.527  23.008  23.042  23.052  22.658  22.952  22.908   
3  21.540  21.419  21.565  20.857  21.052  21.039  20.926  20.912  20.989   
4  20.460  20.298  20.350  19.867  19.997  19.972  19.924  19.813  19.691   

       9   ...      50      51      52      53      54      55      56  \
0  46.599  ...  31.554  30.953  30.639  30.561  30.368  30.224  29.790   
1  27.481  ...  23.995  24.328  24.283  23.877  23.816  23.933  23.354   
2  22.359  ...  21.711  21.564  21.564  21.526  21.753  21.749  21.802   
3  20.882  ...  20.687  20.703  20.295  20.482  20.600  20.547  20.708   
4  19.634  ...  19.887  19.919  19.696  19.634  19.747  20.005  19.919   

       57      58      59  
0  29.261  29.287  28.866  
1  23.483  23.320  23.588  
2  21.582  21.283  21.519  
3  20.708  20.574  20.403  
4  19.736  19.977  20.016  

[5 rows x 60 columns]

In [ ]:
data["CE"]=np.round(data.mean(axis=1),2)

In [ ]:
data.head()

0       1       2       3       4       5       6       7       8  \
0  47.202  47.273  47.250  47.332  47.213  47.372  47.273  47.438  46.691   
1  29.208  28.822  28.805  28.922  28.591  28.643  28.216  27.812  27.514   
2  23.554  23.521  23.527  23.008  23.042  23.052  22.658  22.952  22.908   
3  21.540  21.419  21.565  20.857  21.052  21.039  20.926  20.912  20.989   
4  20.460  20.298  20.350  19.867  19.997  19.972  19.924  19.813  19.691   

        9  ...      51      52      53      54      55      56      57  \
0  46.599  ...  30.953  30.639  30.561  30.368  30.224  29.790  29.261   
1  27.481  ...  24.328  24.283  23.877  23.816  23.933  23.354  23.483   
2  22.359  ...  21.564  21.564  21.526  21.753  21.749  21.802  21.582   
3  20.882  ...  20.703  20.295  20.482  20.600  20.547  20.708  20.708   
4  19.634  ...  19.919  19.696  19.634  19.747  20.005  19.919  19.736   

       58      59     CE  
0  29.287  28.866  39.60  
1  23.320  23.588  25.79  
2  21.283  21.519  22.22  
3  20.574  20.403  20.46  
4  19.977  20.016  19.79  

[5 rows x 61 columns]

In [ ]:
data.drop(data.index[0:60], axis=1, inplace= True)

In [ ]:
data.head()

CE
0  39.60
1  25.79
2  22.22
3  20.46
4  19.79

In [ ]:
files=["TS1","TS2","TS3","TS4","VS1","CP","EPS1","FS1","FS2","PS1","PS2","PS3","PS4","PS5","PS6","SE"]
add= "D:\ML\Hydrolic Data\{}.txt"
for i in files:
    obj=pd.read_csv(add.format(i), sep='\t', header=None)
    
    data[i]= np.round(obj.mean(axis=1),2)


In [ ]:
data.head()

CE    TS1    TS2    TS3    TS4   VS1    CP     EPS1   FS1    FS2  \
0  39.60  35.62  40.98  38.47  31.75  0.58  1.86  2538.93  6.71  10.30   
1  25.79  36.68  41.53  38.98  34.49  0.57  1.26  2531.50  6.72  10.40   
2  22.22  37.88  42.44  39.63  35.65  0.58  1.11  2519.93  6.72  10.37   
3  20.46  38.88  43.40  40.40  36.58  0.57  1.06  2511.54  6.72  10.30   
4  19.79  39.80  44.33  41.31  37.43  0.58  1.07  2503.45  6.69  10.24   

      PS1     PS2   PS3  PS4   PS5   PS6     SE  
0  160.67  109.47  1.99  0.0  9.84  9.73  59.16  
1  160.60  109.35  1.98  0.0  9.64  9.53  59.34  
2  160.35  109.16  1.97  0.0  9.53  9.43  59.54  
3  160.19  109.06  1.95  0.0  9.44  9.34  59.79  
4  160.00  108.93  1.92  0.0  9.36  9.26  59.46

In [ ]:
prof= pd.read_csv("D:\ML\Hydrolic Data\profile.txt", sep="\t", header= None)

In [ ]:
prof.head()

0    1  2    3  4
0  3  100  0  130  1
1  3  100  0  130  1
2  3  100  0  130  1
3  3  100  0  130  1
4  3  100  0  130  1

In [ ]:
data["Cooler_Cond"]=prof[0]
data["Valve_cond"]=prof[1]
data["Int_Pump_Leak"]=prof[2]
data["Hyd_Acc"]= prof[3]
data["Stable_Flag"]=prof[4]
data.head()

CE    TS1    TS2    TS3    TS4   VS1    CP     EPS1   FS1    FS2  ...  \
0  39.60  35.62  40.98  38.47  31.75  0.58  1.86  2538.93  6.71  10.30  ...   
1  25.79  36.68  41.53  38.98  34.49  0.57  1.26  2531.50  6.72  10.40  ...   
2  22.22  37.88  42.44  39.63  35.65  0.58  1.11  2519.93  6.72  10.37  ...   
3  20.46  38.88  43.40  40.40  36.58  0.57  1.06  2511.54  6.72  10.30  ...   
4  19.79  39.80  44.33  41.31  37.43  0.58  1.07  2503.45  6.69  10.24  ...   

    PS3  PS4   PS5   PS6     SE  Cooler_Cond  Valve_cond  Int_Pump_Leak  \
0  1.99  0.0  9.84  9.73  59.16            3         100              0   
1  1.98  0.0  9.64  9.53  59.34            3         100              0   
2  1.97  0.0  9.53  9.43  59.54            3         100              0   
3  1.95  0.0  9.44  9.34  59.79            3         100              0   
4  1.92  0.0  9.36  9.26  59.46            3         100              0   

   Hyd_Acc  Stable_Flag  
0      130            1  
1      130            1  
2      130            1  
3      130            1  
4      130            1  

[5 rows x 22 columns]

In [ ]:
data.to_csv("Hydraulic Data.csv")

In [ ]:
data.isnull().sum()

CE               0
TS1              0
TS2              0
TS3              0
TS4              0
VS1              0
CP               0
EPS1             0
FS1              0
FS2              0
PS1              0
PS2              0
PS3              0
PS4              0
PS5              0
PS6              0
SE               0
Cooler_Cond      0
Valve_cond       0
Int_Pump_Leak    0
Hyd_Acc          0
Stable_Flag      0
dtype: int64

LOGISTIC REGRRESSION CLASSIFICATION FOR COOLER CONDITION

In [ ]:
X=data.iloc[:,:-5].values
y=data.iloc[:,-5].values

In [ ]:
X

array([[39.6 , 35.62, 40.98, ...,  9.84,  9.73, 59.16],
       [25.79, 36.68, 41.53, ...,  9.64,  9.53, 59.34],
       [22.22, 37.88, 42.44, ...,  9.53,  9.43, 59.54],
       ...,
       [46.47, 35.32, 40.88, ...,  9.96,  9.84, 59.13],
       [46.54, 35.32, 40.88, ...,  9.97,  9.85, 58.97],
       [46.65, 35.32, 40.86, ...,  9.97,  9.85, 59.05]])

In [ ]:
y

array([  3,   3,   3, ..., 100, 100, 100], dtype=int64)

In [ ]:
#Spliting the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=10)

In [ ]:
#Scaling the data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [ ]:
X_train

array([[-1.09146463,  1.38294642,  1.43260416, ..., -1.24601178,
        -1.2454234 ,  0.52991696],
       [-0.35431955, -0.16656164, -0.1694218 , ...,  0.02987979,
         0.02040371,  0.16397361],
       [ 1.345856  , -1.12956785, -1.1290246 , ...,  1.15059535,
         1.14156487,  0.11728054],
       ...,
       [-0.35087092, -0.171532  , -0.16404588, ...,  0.02987979,
         0.03848696,  0.05104154],
       [-1.05266752,  1.53951259,  1.49442731, ..., -1.31497889,
        -1.31775638,  0.15094298],
       [-0.34742229, -0.16407646, -0.16673384, ...,  0.01263801,
         0.02040371,  0.28124922]])

In [ ]:
X_test

array([[-0.34483582, -0.15537834, -0.16404588, ..., -0.00460377,
        -0.01576278,  0.29427985],
       [-0.36294113,  0.06580244,  0.05905505, ..., -0.22874688,
        -0.23276171,  0.20089371],
       [ 1.37430721, -1.14199374, -1.13574451, ...,  1.18507891,
         1.17773136,  0.43653082],
       ...,
       [-0.96645172,  1.11703244,  1.15036804, ..., -1.10807755,
        -1.11884069,  0.19872194],
       [-0.99231646,  1.00271429,  1.02806572, ..., -0.97014333,
        -0.97417473,  0.57335237],
       [ 1.34758031, -1.16684551, -1.16396812, ...,  1.20232069,
         1.21389785,  0.42675785]])

In [ ]:
#Training the data
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=10)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=10)

In [ ]:
#Predicting the data
y_pred= classifier.predict(X_test)


In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[214   1   0]
 [  1 224   0]
 [  0   0 222]]


0.9969788519637462

In [ ]:
from sklearn.metrics import precision_score, recall_score
print(precision_score(y_test, y_pred, average="weighted"))
print(recall_score(y_test, y_pred, average="weighted"))
from sklearn.metrics import f1_score
print("f1_score: ", f1_score(y_test, y_pred, average="weighted"))

0.9969788519637462
0.9969788519637462
f1_score:  0.9969788519637462


In [ ]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred, digits=2))

              precision    recall  f1-score   support

           3       1.00      1.00      1.00       215
          20       1.00      1.00      1.00       225
         100       1.00      1.00      1.00       222

    accuracy                           1.00       662
   macro avg       1.00      1.00      1.00       662
weighted avg       1.00      1.00      1.00       662

